language: node_js

node_js:
  - 10

jobs:
  include:
    - stage: eslint
      script:
        - yarn lint
    - stage: release
      script:
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release