language: node_js

node_js:
  - '10'

cache: yarn

jobs:
  include:
    - stage: quality check
      if: branch != master OR (branch = master and type = pull_request)
      script:
        - yarn lint
        - yarn test
    - stage: build & release
      script:
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
        on:
          branch: master
